---

- name: create sap directory
  file:
    path: "/usr/sap/{{ sap_system_id|upper }}"
    state: directory

- name: create sapsys group
  group: name=sapsys gid={{ id_group_sapsys }}

- name: create sapadm user
  user:
    name: sapadm
    uid: "{{ id_user_sapadm }}"
    group: sapsys
    password: "{{ pw_user_sapadm|password_hash('sha512') }}"

- name: create sap sid group
  group: name={{ sap_system_id|lower }}shm gid={{ id_group_shm }}

- name: create sap sid user
  user:
    name: "{{ sap_system_id|lower }}adm"
    uid: "{{ id_user_sidadm }}"
    group: "{{ sap_system_id|lower }}shm"
    home: "/usr/sap/{{ sap_system_id|upper }}/home"
    password: "{{ pw_user_sidadm|password_hash('sha512') }}"

- name: copy installation answer file
  copy: path=hana_install.cfg.j2 dest=/tmp/hana_install_{{ sap_system_id|lower}}.cfg

- name: copy global.ini
  copy: path=global.ini dest=/hana/shared/{{ sap_system_id|upper }}/global.ini

...
