---

- name: apply tuned profile
  shell: /usr/sbin/tuned-adm profile sap-hana
  when: ansible_virtualization_type != 'vmware'

- name: apply tuned profile on VMware systems
  shell: /usr/sbin/tuned-adm profile sap-hana-vmware
  when: ansible_virtualization_type == 'vmware'

- name: disable intel c states in grub config
  lineinfile: dest=/etc/default/grub line=GRUB_CMDLINE_LINUX_DEFAULT="intel_idle.max_cstate=0"
  notify: regenerate grub2 conf

- name: disable selinux
  selinux: state=disabled

- name: set ntp server via chrony
  lineinfile: dest=/etc/chrony.conf line="server {{ ntpserver }} iburst"
  notify: restart chronyd

- name: enable chronyd
  service: name=chronyd state=started enabled=yes

- name: disable firewalld
  service: name=firewalld state=stopped enabled=no

- name: disable kdump
  service: name=kdump state=stopped enabled=no
  ignore_errors: True

- name: disable abrt
  service: name=abrtd state=stopped enabled=no
  ignore_errors: True

- name: disable abrt-ccpp
  service: name=abrt-ccpp state=stopped enabled=no
  ignore_errors: True

- name: disable numad
  service: name=numad state=stopped enabled=no
  ignore_errors: True

...